# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '14.3-DataStorage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'
  # Pods for 14.3-DataStorage

  target '14.3-DataStorageTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '14.3-DataStorageUITests' do
    # Pods for testing
  end

end
